### ISSUE TITLE
Should provide dynamic association option with Arturo::Features

### ISSUE THREAD

**Issue by om-nishu-trantor** [zendesk/arturo#96]
I can blacklist/whitelist Feature Recipient(user/account/anything) based on any third-party factor as mentioned [here ](https://github.com/zendesk/arturo#whitelists--blacklists).
Rather than that, we should have option to associate with Feature itself with the Feature Recipient.
I can do a PR for the polymorphic association with Arturo::Feature model, it might help users like those who need to do custom subscription of plans and enable based on custom selection.

Thoughts ?

**Comment by plukevdh** [comment]
I think whitelist accomplish this as is. What would doing polymorphic association give us that the whitelisting doesn't already? Maybe an example would help clarify what you are trying to do.

**Comment by om-nishu-trantor** [comment]
Feature Recipient <-> Feature

Arturo::Feature.whitelist do |feature, user|
  # Check association here, return true if associated
end

For enabling a feature, just associate the :feature with :feature_recipient

Thoughts ?

**Comment by plukevdh** [comment]
What I would recommend instead is creating this sort of relationship model on your end. This contrived example would totally work:

```ruby
class FeatureRecipient < ActiveRecord::Base
  belongs_to :feature_proxy

  def allowed?(feature)
    feature_proxy.feature == feature
  end
end

class FeatureProxy < ActiveRecord::Base
  has_many :feature_recipients
  belongs_to :feature, class_name: Arturo::Feature
end

feature = Arturo::Feature.find_feature(:awesome_feature)

proxy = FeatureProxy.create(feature: feature)
proxy.feature_recipients << FeatureRecipient.new(name: "Bob Dylan")
# etc... 

Arturo::Feature.whitelist(:awesome_feature) do |feature, user|
  user.allowed?(feature)
end
```

You can always change the 1-n relationship of the proxy-users relationship to allow for a user to have multiple allowed feature groups. Whitelists are flexible enough to give you what you want without needing to change the internals of the Feature model. 

@grosser or @jamesarosen can reopen if they like, but I think your desired behavior is something that can be done already given the existing functionality.

**Comment by om-nishu-trantor** [comment]
```ruby
Arturo::FeatureAvailability.class_eval do
    def feature_recipient
      account = current_user.account
      # 
      account.instance_eval do
        def allowed?(feature)
          !!(RecipientProxy.find_by(recipient: self, feature: feature))
        end
      end

      account.class.has_many(:recipient_proxies, foreign_key: :recipient_id)
      account.class.has_many(:features, through: :recipient_proxies)
      Arturo::Feature.has_many(:recipient_proxies)
      Arturo::Feature.has_many(:recipients, through: :recipient_proxies)
      RecipientProxy.belongs_to(:recipient, class_name: account.class)
      # 
      return account
    end
  end

  Arturo::Feature.whitelist(:awesome_feature) do |account|
    account.allowed?(Arturo::Feature.find_by(symbol: :awesome_feature))
  end
```

**Comment by plukevdh** [comment]
If this is the kind of code you want to support, that's up to you and your requirements. Arturo has the capabilities to do what you are asking without requiring injecting knowledge of a relationship to an external model (the `Recipient` model in this example) into Arturo's code. Arturo 3.0 (#39) is hoping to remove most of the dependence on Rails and be more Rack-centric, which would mean adding support for relational logic using ActiveRecord models like this is not worth the effort. If you want to spend the time to write up a PR, you are more than welcome to do so, but I personally have no interest in supporting this special case feature.
